name = "ai-models"
description = "Download AI models and add them to your Spin application."
version = "0.2.0"
spin_compatibility = ">=1.3"
license = "Apache-2.0"
homepage = "https://github.com/itowlson/spin-ai-models"
package = "./target/release/spin-ai-models"
